version: '2'
services:
  client:
    # Step 5.1 - Point build step to the client directory
    build: './banking-application'
    ports:
      # Step 5.2 - Add the port that the banking-application runs on - (port:port).
      - '3000:3000'
    depends_on:
      - server
  server:
    # Step 5.3 - Point build step to the backend directory

    build: './backend'
    ports:

      # Step 5.4 - Add the port that the server application runs on - (port:port).
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo:3.0.2
    ports:
      - '27017:27017'
    restart: always  